### ISSUE TITLE
Takedown Notice//cc proxies now removed

### ISSUE THREAD

**Issue by Asleep123** [S-PScripts/proxies-hubs#1]
Hello, I am an administrator of Art Class.

Looks like you have some premium links in your list of links.  (https://raw.githubusercontent.com/S-PScripts/proxies-hubs/main/proxy%20links).
This goes against our rules.

The original links can be found in our #links channel in our Discord (discord.gg/desmos).
We pay money for those links, and I do not appreciate you taking them without proper consent.

I hereby request takedown on your repository (proxies-hubs). Please comply with this request or further action may be taken upon your repository.

Asleep 
Administrator at Art Class

**Comment by S-PScripts** [comment]
Blanked out the whole proxy page and I'll remove art class, shuttle, bigfoot's game shack and other sites if I were to get asked.

**Comment by Asleep123** [comment]
You are not allowed to host this anywhere else available to the public.

**Comment by S-PScripts** [comment]
It's not available to the public, I have it on some Google doc that has no permissions for anyone else to look at.
